Repository straumandi/armanious_schmatz, pull requests merged in 2025-01, with the labels that each got.

#1 Documentation
  CHECKLIST.md
  README.md
  docu/branching_strategy.md
  docu/general.md
Labels: documentation

#3 Add basic workflow for CI/CD with deployment to Github Pages
  .github/workflows/ci-cd-github-pages.yml
Labels: enhancement

#9 Add tests
  .github/workflows/ci-cd-github-pages.yml
  CHECKLIST.md
  docu/general.md
  src/__tests__/TaskList.test.jsx
Labels: enhancement

#13 Try fixing iac
  .github/workflows/ci-cd-github-pages.yml
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-to-EC2.yml
  .gitignore
  Dockerfile
  ansible/deploy.yml
  ansible/inventory.yml
  ansible/playbook.yml
  terraform/credentials.template
  terraform/main.tf
  terraform/outputs.tf
  terraform/variables.tf
Labels: bug

#12 Add CI/CD Pipeline with AWS EC2 Deployment
  .github/workflows/ci-cd-github-pages.yml
  .github/workflows/ci-cd.yml
  .gitignore
  Dockerfile
  ansible/playbook.yml
  ecosystem.config.js
  terraform/.terraform.lock.hcl
  terraform/.terraform/providers/registry.terraform.io/hashicorp/aws/5.82.2/darwin_arm64/LICENSE.txt
  terraform/main.tf
  terraform/outputs.tf
  terraform/terraform.tfstate
  terraform/terraform.tfstate.backup
  terraform/variables.tf
Labels: enhancement

#14 update checklist
  CHECKLIST.md
Labels: documentation

#16 try fixing multiple instances
  .github/workflows/ci-cd.yml
  terraform/main.tf
  terraform/outputs.tf
Labels: bug

#20 Add security and dependency check to pipeline
  .github/workflows/ci-cd.yml
  .zap/rules.tsv
Labels: automation
